export const DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];

export const DAY_LABELS = {
  monday: 'Mon',
  tuesday: 'Tue',
  wednesday: 'Wed',
  thursday: 'Thu',
  friday: 'Fri',
  saturday: 'Sat',
  sunday: 'Sun'
};

export const DAY_FULL = {
  monday: 'Monday',
  tuesday: 'Tuesday',
  wednesday: 'Wednesday',
  thursday: 'Thursday',
  friday: 'Friday',
  saturday: 'Saturday',
  sunday: 'Sunday'
};

export const MEALS = [
  { key: 'breakfast', label: 'Breakfast', time: '7:30 - 9:00 AM', emoji: '🍳', icon: '☀️' },
  { key: 'lunch', label: 'Lunch', time: '12:00 - 2:00 PM', emoji: '🍛', icon: '🌤️' },
  { key: 'snacks', label: 'Snacks', time: '4:30 - 5:30 PM', emoji: '🍪', icon: '🌅' },
  { key: 'dinner', label: 'Dinner', time: '7:30 - 9:00 PM', emoji: '🍽️', icon: '🌙' },
];

export const menuData = {
  monday: {
    breakfast: ['VEN PONGAL', 'TIFFIN SAMBAR', 'COCONUT CHUTNEY', 'MEDU VADA', 'MASALA OMELETTE / WHOLE WHEAT BREAD OMELETTE - 1 NO', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM', 'MILK', 'FILTER COFFEE', 'PLAIN TEA'],
    lunch: ['METHI CHAPATHI', 'BLACK CHANNA MASALA', 'LEMON RICE / TAMARIND RICE', 'DAL MAKHANI', 'STEAMED RICE', 'ARACHIVITTA SAMBAR', 'KEERAI KOOTU', 'LEMON RASAM', 'CURD - 100 ML', 'PARUPPU PODI', 'GHEE', 'OIL', 'FRYUMS', 'PICKLE', 'BUTTERMILK'],
    snacks: ['SAMOSA / VEG ROLL - 1 NO', 'MILK', 'ROSE MILK / BADAM MILK', 'TEA', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM'],
    dinner: ['BAGAARA PULAO / IDLI', 'RAITA / CHUTNEY', 'CHAPATHI', 'PANEER GRAVY / BABY CORN GRAVY', 'STEAMED RICE', 'PUMPKIN SAMBAR', 'DAL RASAM', 'BUTTERMILK', 'PICKLE', 'GREEN SALAD', 'MILK', 'BANANA', 'NON-VEG: ANDHRA CHICKEN CURRY - 120 GM / FISH FRY - 1 NO & FISH GRAVY (FLAVORED GRAVY)']
  },
  tuesday: {
    breakfast: ['VEG RAVA KITCHADI/VEG UPMA', 'TIFFIN SAMBAR', 'ONION/COCONUT CHUTNEY', 'POORI', 'ALOO MASALA', 'BOILED EGG - 1 NO', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM', 'MILK', 'FILTER COFFEE', 'PLAIN TEA'],
    lunch: ['CHAPATHI', 'WHITE PEAS CURRY', 'JEERA PULAO', 'YELLOW DAL', 'STEAMED RICE', 'VATHAKUZHAMBU / MORE KUZHAMBU', 'PORIYAL', 'TOMATO RASAM', 'CURD - 100 ML', 'PARUPPU PODI', 'GHEE', 'OIL', 'FRYUMS', 'PICKLE', 'BUTTERMILK', 'PAYASAM'],
    snacks: ['PANI POORI - 5 NOS / PAV BHAJI - 1 NO', 'MILK', 'FILTER COFFEE', 'GINGER TEA', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM'],
    dinner: ['ONION UTHAPPAM', 'KARA CHUTNEY', 'MILLETS CHAPATHI', 'DAL PANCHARATHAN', 'IDLI PODI', 'OIL', 'STEAMED RICE', 'RADISH SAMBAR', 'LEMON RASAM', 'BUTTERMILK', 'PICKLE', 'GREEN SALAD', 'MILK', 'SEASONAL FRUITS', 'NON-VEG: EGG GRAVY (FLAVORED GRAVY)']
  },
  wednesday: {
    breakfast: ['IDIYAPPAM', 'VADA CURRY/ VEG STEW', 'POHA', 'MINT CHUTNEY', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM', 'MILK', 'FILTER COFFEE', 'PLAIN TEA'],
    lunch: ['BEETROOT CHAPATHI', 'RAJMA MASALA', 'SAMBAR RICE / TOMATO RICE', 'DAL FRY', 'STEAMED RICE', 'URULAI KARA CURRY', 'GARLIC RASAM', 'CURD RICE', 'PARUPPU PODI', 'GHEE', 'OIL', 'APPALAM', 'PICKLE', 'BUTTERMILK'],
    snacks: ['CREAM BUN - 1 NO / OSAMANIA BISCUITS - 2 NOS', 'MILK', 'FILTER COFFEE', 'MASALA TEA', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM'],
    dinner: ['KAL DOSA', 'TOMATO CHUTNEY', 'CHAPATHI', 'PANEER BUTTER MASALA', 'STEAMED RICE', 'MASALA SAMBAR', 'PINEAPPLE RASAM', 'BUTTERMILK', 'PICKLE', 'GREEN SALAD', 'MILK', 'BANANA', 'NON-VEG: CHICKEN CURRY WITH 120 GM CHICKEN / CHICKEN BIRYANI WITH BOILED EGG - 1 NO']
  },
  thursday: {
    breakfast: ['IDLI', 'UDUPI SAMBAR', 'GROUNDNUT CHUTNEY', 'MEDU VADA', 'CORN FLAKES', 'IDLI PODI', 'OIL', 'BOILED EGG - 1 NO', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM', 'MILK', 'FILTER COFFEE', 'PLAIN TEA'],
    lunch: ['CHAPATHI', 'VEGETABLE SABJI', 'GHEE PULAO', 'TOMATO DAL FRY', 'STEAMED RICE', 'VATHAKUZHAMBU', 'VEGETABLE KOOTU', 'GINGER RASAM', 'CURD - 100 ML', 'PARUPPU PODI', 'GHEE', 'OIL', 'FRYUMS', 'PICKLE', 'BUTTERMILK', 'BONDHI'],
    snacks: ['MASALA SUNDAL - 100 ML', 'MILK', 'FILTER COFFEE', 'CARDAMOM TEA', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM'],
    dinner: ['UTHAPPAM', 'VEGETABLE CHUTNEY', 'CHOLE POORI MATAR', 'CHANNA MASALA', 'STEAMED RICE', 'KATHIRIKAI SAMBAR', 'TOMATO RASAM', 'BUTTERMILK', 'PICKLE', 'GREEN SALAD', 'MILK', 'ARUN CHOCO BAR / CONE ICE CREAM - 1 NO', 'NON-VEG: CHETTINADU MUTTON KUZHAMBU(FLAVOURED GRAVY)']
  },
  friday: {
    breakfast: ['KAL DOSA', 'TIFFIN SAMBAR', 'ONION / TOMATO CHUTNEY', 'SEMIYA BHATH', 'IDLI PODI', 'OIL', 'OMELETTE / WHOLE WHEAT BREAD OMELETTE - 1 NO', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM', 'MILK', 'FILTER COFFEE', 'PLAIN TEA'],
    lunch: ['CHAPATHI', 'ALOO PALAK', 'PEAS PULAO', 'DAL TADKA', 'STEAMED RICE', 'SAMBAR', 'BEETROOT PORIYAL', 'PULI RASAM', 'CURD - 100 ML', 'PARUPPU PODI', 'GHEE', 'OIL', 'APPALAM', 'PICKLE', 'BUTTERMILK'],
    snacks: ['MURUKKU - 2 NOS', 'MILK', 'MINT LEMON JUICE', 'TEA', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM'],
    dinner: ['PASTA(BECHAMEL/ARRABBIATA) / VEG SCHEZWAN FRIED RICE(MANCHURIAN)', 'SOUP', 'CHAPATHI', 'KADAI VEGETABLES', 'STEAMED RICE', 'MIX VEG SAMBAR', 'PEPPER RASAM', 'BUTTERMILK', 'PICKLE', 'GREEN SALAD', 'MILK', 'BANANA', 'NON-VEG: CHICKEN GRAVY (FLAVORED GRAVY)']
  },
  saturday: {
    breakfast: ['IDLI', 'CHINNA VENGAYA SAMBAR', 'GROUNDNUT CHUTNEY', 'ALOO PARATHA', 'CURD - 100 ML', 'IDLI PODI', 'OIL', 'BOILED EGG - 1 NO', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM', 'MILK', 'FILTER COFFEE', 'PLAIN TEA'],
    lunch: ['CHAPATHI', 'MEAL MAKER KURMA', 'VEGETABLE DUM BIRYANI', 'RAITHA', 'STEAMED RICE', 'KEERAI KOOTU', 'JEERA RASAM', 'CURD RICE', 'PARUPPU PODI', 'GHEE', 'OIL', 'FRYUMS', 'PICKLE', 'BUTTERMILK', 'GULAB JAMUN / BADHUSHAH'],
    snacks: ['EGGLESS CAKE / CHOCOLATE BROWNIE - 1 NO', 'MILK', 'FILTER COFFEE', 'MASALA TEA', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM'],
    dinner: ['KAL DOSA', 'CHUTNEY', 'CHAPATHI', 'VEG SALNA', 'IDLI PODI', 'OIL', 'STEAMED RICE', 'KARAIKUDI SAMBAR', 'GARLIC RASAM', 'BUTTERMILK', 'PICKLE', 'GREEN SALAD', 'MILK', 'BANANA', 'NON-VEG: CHICKEN GRAVY (FLAVORED GRAVY)']
  },
  sunday: {
    breakfast: ['CHOLE BHATURA', 'CHOLE MASALA', 'KAL DOSA', 'COCONUT CHUTNEY', 'SAMBAR', 'IDLI PODI', 'OIL', 'EGG KAL DOSA - 1 NO', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM', 'MILK', 'FILTER COFFEE', 'PLAIN TEA'],
    lunch: ['CHAPATHI', 'CHICKEN CURRY WITH 120 GM CHICKEN', 'PANEER GRAVY', 'STEAMED RICE', 'CHETTINAD SAMBAR', 'BEETROOT PORIYAL', 'DAL RASAM', 'CURD - 100 ML', 'PARUPPU PODI', 'GHEE', 'OIL', 'FRYUMS', 'PICKLE', 'BUTTERMILK', 'ARUN CUP ICE CREAM - 1 NO'],
    snacks: ['CHANNA SUNDAL(WHITE/BLACK) - 100 ML', 'MILK', 'FILTER COFFEE', 'GINGER TEA', 'WHOLE WHEAT BREAD', 'BUTTER', 'JAM'],
    dinner: ['DAL KHICHDI', 'CHAPATHI', 'VEG KURMA', 'PORIYAL', 'STEAMED RICE', 'KADAMBA SAMBAR', 'RASAM', 'BUTTERMILK', 'PICKLE', 'GREEN SALAD', 'MILK', 'BANANA', 'NON-VEG: CHICKEN GRAVY(FLAVORED GRAVY)']
  }
};
